version: "3.8"

services:
  kong:
    image: kong:latest
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_PASSWORD: kong
    ports:
      - "8000:8000" # Proxy
      - "8001:8001" # Admin API
      - "8443:8443" # Proxy SSL
      - "8444:8444" # Admin API SSL
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-kong:
    image: postgres:latest
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysqldb:
    image: mysql:8.0.29
    environment:
      MYSQL_DATABASE: "my_db"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - my-db:/var/lib/mysql
      - ./scripts/mysqldb_update_privileges.sh:/docker-entrypoint-initdb.d/mysqldb_update_privileges.sh
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

  service-one:
    build: ../../downstream-services/service-one
    image: service-one:1.0
    depends_on:
      - kong
    ports:
      - "3001:3001"


  service-two:
    build: ../../downstream-services/service-two
    image: service-two:1,0
    depends_on:
      - kong
    ports:
      - "3002:3002"


  auth-service:
    build: ../../authentication
    image: auth-service:1.0
    depends_on:
      - kong
      - redis
      - postgres
    ports:
      - "3003:3003"


  client:
    build: ../../frontend
    image: client:1.0
    depends_on:
      - service-one
      - service-two

  redis:
    image: redis:7.2-rc2-alpine3.18
    command: redis-server --requirepass password
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "password", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  kong-db:
