name: Lint and Fix

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  

    - name: Install dependencies
      run: |
        cd Authentication
        npm install
        cd ../frontend
        npm install

    - name: Run lint:fix
      run: |
        cd Authentication
        npm run lint:fix
        cd ../frontend
        npm run lint:fix
