name: Lint and Fix

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  

    - name: Install dependencies in authentication directory
      run: |
        cd authentication
        npm install

    - name: Run lint:fix in authentication directory
      run: |
        cd authentication
        npm run lint:fix

    - name: Install dependencies in frontend directory
      run: |
        cd frontend
        npm install

    - name: Run lint:fix in frontend directory
      run: |
        cd frontend
        npm run lint:fix
